# Generated by Django 6.0.2 on 2026-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='required_organ',
            field=models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lung', 'Lung'), ('Blood', 'Blood')], max_length=50),
        ),
    ]
