# Generated by Django 6.0.2 on 2026-03-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recipient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='success_rate',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='50%', max_length=5),
        ),
    ]
